import {S,defProfile,load,save,today,clamp} from './storage.js';
import {renderCoach} from './coach.js';
import {recoveryScore,workTime,restTime,fatigueMap} from './recovery.js';
import {loadMissions,chooseMission,missionMuscles} from './missions.js';
import {loadExercises,exByName,exerciseCard} from './academy.js';
import {lastWeight,prediction,ranks,achievementStatus} from './analytics.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let profile=load(S.profile,defProfile),log=load(S.log,[]),coach=load(S.coach,{sleep:7,energy:3,soreness:1,sport:'none',bar:true,notes:''}),body=load(S.body,[]),photos=load(S.photos,[]);
let exercises=[],missions=[],running=false,tick=null,idx=0,phase='work',time=45;
async function init(){exercises=await loadExercises();missions=await loadMissions();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});initTabs();renderAll()}
function openTab(t){$$('.tab').forEach(x=>x.classList.toggle('active',x.id===t));$$('.tabbtn').forEach(x=>x.classList.toggle('active',x.dataset.tab===t));localStorage.setItem(S.tab,t);renderAll()}
function initTabs(){const tab=localStorage.getItem(S.tab)||'coach';$$('.tabbtn').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));openTab(tab)}
function renderAll(){const active=$$('.tab').find(x=>x.classList.contains('active'))?.id||'coach';if(active==='coach')renderCoach({profile,coach,log,missions,onSave:c=>{coach=c;renderAll()},onGo:c=>{coach=c;idx=0;phase='work';time=workTime(recoveryScore(coach));openTab('mission')}});if(active==='mission')renderMission();if(active==='academy')renderAcademy();if(active==='body')renderBody();if(active==='progress')renderProgress()}
function currentMission(){return chooseMission({missions,profile,coach,log})}
function renderMission(){const m=currentMission();const score=recoveryScore(coach);const list=m.exercises.map(n=>exByName(exercises,n));const e=list[idx%list.length];$('#mission').innerHTML=`<div class="card"><div class="label">${m.phase} · Recovery ${score}%</div><div class="h2">${m.title}</div><div class="small">${m.coachNote}</div><div class="grid3" style="margin-top:12px"><div class="stat"><b>${m.duration}</b><span>minutos</span></div><div class="stat"><b>${m.intensity}</b><span>intensidade</span></div><div class="stat"><b>${profile.mission}</b><span>nº missão</span></div></div></div><div class="card"><div class="label">${phase==='work'?'Trabalho':'Descanso'}</div><div class="h2">${e.name}</div><img class="exerciseHero" src="${e.imageStart}"><div class="timer">${time}s</div><div class="small">${e.cues}</div><div class="grid2" style="margin-top:12px"><button class="btn primary" id="startStop">${running?'Pausar':'Iniciar'}</button><button class="btn soft" id="nextEx">Próximo</button></div></div><div class="card"><div class="label">Plano de hoje</div>${list.map((x,i)=>`<div class="item"><img src="${x.imageStart}"><div><b>${i+1}. ${x.name}</b><span class="small">${x.group} · ${x.tempo}</span></div></div>`).join('')}<button class="btn primary" id="finish" style="width:100%;margin-top:10px">Concluir missão</button></div>${exerciseCard(e)}`;$('#startStop').onclick=toggleTimer;$('#nextEx').onclick=()=>{nextInterval();renderMission()};$('#finish').onclick=finishMission}
function toggleTimer(){running=!running;if(tick)clearInterval(tick);if(running){tick=setInterval(()=>{time--;if(time<=0)nextInterval();renderMission()},1000)}renderMission()}
function nextInterval(){const score=recoveryScore(coach);if(phase==='work'){phase='rest';time=restTime(score)}else{phase='work';idx++;time=workTime(score)} }
function finishMission(){const m=currentMission();const d=today();const already=profile.lastDate===d;profile.xp+=already?20:100+Math.round(recoveryScore(coach)/5);profile.streak=already?profile.streak+0:profile.streak+1;profile.lastDate=d;profile.mission=(profile.mission%365)+1;profile.plan='auto';log.push({date:d,key:m.key,title:m.title,score:recoveryScore(coach),muscles:missionMuscles(m)});save(S.profile,profile);save(S.log,log);running=false;if(tick)clearInterval(tick);idx=0;phase='work';time=workTime(recoveryScore(coach));openTab('progress')}
function renderAcademy(){const q=($('#q')?.value||'').toLowerCase();const filtered=exercises.filter(e=>(e.name+e.group+e.secondary).toLowerCase().includes(q)).slice(0,40);$('#academy').innerHTML=`<div class="card"><div class="label">v27.1 Academia</div><div class="h2">Biblioteca técnica</div><div class="small">${exercises.length} exercícios/variantes, imagens SVG offline, progressões, regressões e erros frequentes.</div><input class="search" id="q" placeholder="Pesquisar exercício ou músculo" value="${q}"></div>${filtered.map(exerciseCard).join('')}`;$('#q').oninput=renderAcademy}
function renderBody(){const latest=body.at(-1)||{};$('#body').innerHTML=`<div class="card"><div class="label">v27.3 Body Analytics</div><div class="h2">Peso, perímetros e fotos</div><div class="grid3" style="margin-top:12px"><div class="stat"><b>${lastWeight(body,profile).toFixed(1)}</b><span>kg atual</span></div><div class="stat"><b>${(profile.targetWeight-lastWeight(body,profile)).toFixed(1)}</b><span>kg falta</span></div><div class="stat"><b>${profile.protein}</b><span>g proteína</span></div></div></div><div class="card"><div class="grid2"><div class="field"><label>Peso kg</label><input id="bw" type="number" step="0.1" value="${latest.weight||lastWeight(body,profile)}"></div><div class="field"><label>Braço cm</label><input id="arm" type="number" step="0.1" value="${latest.arm||''}"></div><div class="field"><label>Peito cm</label><input id="chest" type="number" step="0.1" value="${latest.chest||''}"></div><div class="field"><label>Cintura cm</label><input id="waist" type="number" step="0.1" value="${latest.waist||''}"></div></div><button class="btn primary" id="saveBody">Guardar medidas</button></div><div class="card"><div class="label">Fotos mensais</div><div class="small">Guarda frente/lado/costas com luz e pose semelhantes. Comparação visual 100% offline.</div><div class="field"><label>Ângulo</label><select id="angle"><option>frente</option><option>lado</option><option>costas</option></select></div><input id="photoInput" type="file" accept="image/*"><div class="grid2" style="margin-top:12px">${photos.slice(-4).map(p=>`<img class="photo" src="${p.data}">`).join('')||'<div class="small">Sem fotos ainda.</div>'}</div></div><div class="card"><div class="label">Histórico</div>${body.slice(-8).reverse().map(b=>`<div class="item"><div><b>${b.date} · ${b.weight} kg</b><span class="small">Braço ${b.arm||'—'} · Peito ${b.chest||'—'} · Cintura ${b.waist||'—'}</span></div></div>`).join('')||'<div class="small">Ainda sem medições.</div>'}</div>`;$('#saveBody').onclick=()=>{body.push({date:today(),weight:+$('#bw').value,arm:$('#arm').value,chest:$('#chest').value,waist:$('#waist').value});save(S.body,body);renderBody()};$('#photoInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{photos.push({date:today(),angle:$('#angle').value,data:rd.result});save(S.photos,photos);renderBody()};rd.readAsDataURL(f)}}
async function renderProgress(){const ach=await fetch('data/achievements.json').then(r=>r.json());const rank=(ranks().filter(x=>profile.xp>=x.xp).at(-1)||ranks()[0]);const next=ranks().find(x=>profile.xp<x.xp)||ranks().at(-1);const pct=clamp(profile.xp/next.xp*100,0,100);const weight=lastWeight(body,profile);const f=fatigueMap(log);$('#progress').innerHTML=`<div class="card"><div class="label">v28 Dashboard</div><div class="rank">${rank.name}</div><div class="small">XP ${profile.xp} / ${next.xp}</div><div class="bar"><div class="fill" style="width:${pct}%"></div></div></div><div class="card"><div class="grid3"><div class="stat"><b>${log.length}</b><span>missões</span></div><div class="stat"><b>${profile.streak}</b><span>streak</span></div><div class="stat"><b>${(weight-profile.startWeight).toFixed(1)}</b><span>kg ganhos</span></div><div class="stat"><b>${Math.round(log.length*15/60)}</b><span>horas</span></div><div class="stat"><b>${Math.max(0,(profile.targetWeight-weight)).toFixed(1)}</b><span>kg falta</span></div><div class="stat"><b>${recoveryScore(coach)}%</b><span>recovery</span></div></div></div><div class="card"><div class="label">Modelo muscular preditivo</div><div class="h2">${prediction(body,profile)}</div><div class="small">Baseado em dados locais: peso, missões, recovery e consistência.</div></div><div class="card"><div class="label">Fadiga por grupos</div>${Object.entries(f).map(([k,v])=>`<div><div class="row"><span>${k}</span><span>${Math.round(v)}%</span></div><div class="bar"><div class="fill" style="width:${clamp(v,0,100)}%"></div></div></div>`).join('')}</div><div class="card"><div class="label">Conquistas</div>${ach.map(a=>`<div class="item"><div><b>${achievementStatus(a,{log,weight})?'✅':'⬜'} ${a.name}</b><span class="small">${a.desc}</span></div></div>`).join('')}</div>`}
init();
