(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const S={profile:'mb28_profile',log:'mb28_log',coach:'mb28_coach',body:'mb28_body',photos:'mb28_photos',tab:'mb28_tab',settings:'mb28_settings'};
const defProfile={age:48,height:173,startWeight:61,targetWeight:66,protein:125,creatine:true,mission:1,xp:0,streak:0,lastDate:'',plan:'auto'};
let profile=load(S.profile,defProfile), log=load(S.log,[]), coach=load(S.coach,{sleep:7,energy:3,soreness:1,sport:'none',bar:true,mood:'normal'}), body=load(S.body,[]), photos=load(S.photos,[]), running=false, idx=0, phase='work', time=45, tick=null;
function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}; function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function today(){return new Date().toISOString().slice(0,10)}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
const muscles={peito:'#0a84ff',ombros:'#5e5ce6',triceps:'#ff9f0a',costas:'#30b0c7',biceps:'#34c759',core:'#ff375f'};
const E=[
{name:'Power Twister press horizontal',group:'peito',sec:'ombros/tríceps',level:3,tempo:'3-1-4',why:'Tensão mecânica alta no peitoral sem precisar de banco ou pesos.',setup:'Barra à frente do peito, cotovelos ligeiramente abaixo dos ombros, punhos neutros.',exec:'Fecha a barra até ao ponto forte, mantém 1 segundo e abre devagar sem perder controlo escapular.',breath:'Expira a fechar; inspira na fase lenta de abertura.',mistake:'Elevar os ombros e encurtar a amplitude.',reg:'Fecha só 60–70% da amplitude.',prog:'Pausa isométrica final de 3–5 s.',cues:'Peito alto · escápulas baixas · lento a abrir'},
{name:'Power Twister press alto',group:'peito',sec:'ombros/tríceps',level:3,tempo:'3-1-4',why:'Aumenta o foco no peitoral superior e deltoide anterior.',setup:'Barra à frente da linha clavicular, cotovelos altos mas sem encolher trapézios.',exec:'Comprime num arco curto e forte; controla a abertura.',breath:'Expira na compressão.',mistake:'Compensar com lombar.',reg:'Faz sentado.',prog:'Isometria de 20 s no final.'},
{name:'Power Twister overhead press',group:'ombros',sec:'tríceps/peito',level:4,tempo:'2-1-4',why:'Press vertical com resistência progressiva para deltoide anterior e serrátil.',setup:'Barra acima da cabeça, abdómen contraído, costelas para baixo.',exec:'Fecha a barra sem arquear a lombar; regressa devagar.',breath:'Expira ao fechar.',mistake:'Hiperlordose lombar.',reg:'Faz à frente da testa.',prog:'Mantém 10–20 s a meia compressão.'},
{name:'Power Twister remada isométrica',group:'costas',sec:'bíceps/romboides',level:3,tempo:'hold',why:'Cria trabalho escapular e tensão posterior, essencial para equilibrar as flexões.',setup:'Segura a barra à frente, tenta puxar as extremidades para fora enquanto retrais escápulas.',exec:'Mantém tensão 20–40 s, peito aberto, pescoço relaxado.',breath:'Respiração curta e controlada.',mistake:'Fletir pescoço ou rodar ombros para a frente.',reg:'Menos tensão.',prog:'Alterna 5 s máximo / 5 s submáximo.'},
{name:'Power Twister curl isométrico',group:'biceps',sec:'antebraço',level:3,tempo:'hold',why:'Dá estímulo direto ao bíceps, difícil em calistenia sem barra de elevações.',setup:'Cotovelos junto ao tronco, barra na frente, punhos neutros.',exec:'Tenta curvar/fechar a barra como se fizesses curl, mantendo 90°.',breath:'Não bloqueies a respiração.',mistake:'Abrir cotovelos.',reg:'10–15 s.',prog:'30–45 s ou pulsos curtos.'},
{name:'Power Twister reverse press',group:'triceps',sec:'peito/ombros',level:3,tempo:'3-1-3',why:'Ênfase em tríceps e cadeia de empurrar.',setup:'Pega invertida, cotovelos perto do corpo.',exec:'Comprime mantendo cotovelos estáveis.',breath:'Expira na compressão.',mistake:'Rodar punhos com dor.',reg:'Amplitude parcial.',prog:'Negativas lentas.'},
{name:'Flexão declinada',group:'peito',sec:'ombros/tríceps',level:4,tempo:'3-1-2',why:'Prioriza peitoral superior e ombro anterior, excelente para físico em V.',setup:'Pés elevados se possível; se não, posição normal com mãos ligeiramente atrás da linha do peito.',exec:'Desce lento, pausa curta, sobe forte.',breath:'Inspira a descer; expira a subir.',mistake:'Bacia a cair.',reg:'Flexão normal.',prog:'Pseudo-planche.'},
{name:'Flexão diamante',group:'triceps',sec:'peito',level:4,tempo:'3-1-2',why:'Tríceps e peitoral interno com alto estímulo em pouco tempo.',setup:'Mãos próximas em diamante ou apenas à largura dos ombros se houver desconforto.',exec:'Desce controlado com cotovelos próximos.',mistake:'Forçar punhos.',reg:'Mãos fechadas, não diamante.',prog:'Pausa baixa.'},
{name:'Pike push-up',group:'ombros',sec:'tríceps/core',level:4,tempo:'3-1-2',why:'O melhor substituto de press militar sem pesos.',setup:'Bacia alta, cabeça entre braços, calcanhares podem estar elevados.',exec:'Desce a cabeça em direção ao chão, empurra o chão para longe.',mistake:'Transformar em flexão normal.',reg:'Menos inclinação.',prog:'Pés elevados.'},
{name:'Pseudo-planche lean',group:'ombros',sec:'peito/core',level:4,tempo:'hold',why:'Aumenta a alavanca sobre deltoide anterior e peitoral.',setup:'Mãos no chão perto da cintura, inclina ombros à frente.',exec:'Mantém 15–40 s sem perder protração escapular.',mistake:'Cotovelos dobrados sem controlo.',reg:'Inclinação menor.',prog:'Pseudo-planche push-up.'},
{name:'Back widow',group:'costas',sec:'romboides',level:3,tempo:'2-1-3',why:'Remada posterior no chão para costas altas, sem equipamento.',setup:'Deitado de costas, cotovelos no chão a 45–70°.',exec:'Empurra cotovelos contra o chão e eleva o tórax.',mistake:'Usar impulso cervical.',reg:'Menor amplitude.',prog:'Pausa de 3 s em cima.'},
{name:'Reverse snow angel',group:'costas',sec:'ombros posteriores',level:2,tempo:'2-1-3',why:'Reforça trapézio médio/inferior e ombro posterior.',setup:'Deitado de barriga para baixo, braços estendidos.',exec:'Move braços em arco, polegares para cima.',mistake:'Encolher ombros.',reg:'Amplitude menor.',prog:'Pausa no topo.'},
{name:'Prone lat pull',group:'costas',sec:'core',level:2,tempo:'2-1-3',why:'Simula puxada lat e ensina depressão escapular.',setup:'Barriga para baixo, braços à frente.',exec:'Puxa cotovelos para as costelas, contraindo dorsais.',mistake:'Levantar lombar demasiado.',reg:'Movimento curto.',prog:'Isometria 2 s.'},
{name:'Bodyweight triceps extension',group:'triceps',sec:'core',level:4,tempo:'3-1-2',why:'Extensão direta de tríceps sem equipamento.',setup:'Mãos no chão à frente, corpo em prancha inclinada.',exec:'Dobra cotovelos levando testa em direção às mãos; estende.',mistake:'Abrir cotovelos.',reg:'Joelhos no chão.',prog:'Mais inclinação.'},
{name:'Close-grip push-up',group:'triceps',sec:'peito',level:3,tempo:'3-1-2',why:'Empurrar pesado com foco em tríceps.',setup:'Mãos à largura dos ombros, cotovelos próximos.',exec:'Desce lento; sobe sem perder linha corporal.',mistake:'Cotovelos abertos.',reg:'Joelhos no chão.',prog:'1.5 reps.'},
{name:'Hollow hold',group:'core',sec:'flexores anca',level:3,tempo:'hold',why:'Constrói abdómen anti-extensão e transferência para flexões/press.',setup:'Deitado, lombar colada ao chão.',exec:'Eleva ombros e pernas; mantém costelas para baixo.',mistake:'Lombar descolar.',reg:'Joelhos fletidos.',prog:'Hollow rocks.'},
{name:'Leg raises',group:'core',sec:'abdómen inferior',level:3,tempo:'3-1-3',why:'Espessura abdominal e controlo pélvico.',setup:'Deitado, mãos junto ao corpo.',exec:'Sobe pernas sem balanço; desce sem perder lombar.',mistake:'Arco lombar.',reg:'Joelhos fletidos.',prog:'Pausa baixa.'},
{name:'Mountain climbers',group:'core',sec:'condicionamento',level:2,tempo:'rápido',why:'Densidade metabólica sem perder foco no core.',setup:'Prancha alta.',exec:'Alterna joelhos ao peito mantendo ombros estáveis.',mistake:'Bacia aos saltos.',reg:'Mais lento.',prog:'Cross-body.'},
{name:'Shoulder taps',group:'ombros',sec:'core/serrátil',level:2,tempo:'controlado',why:'Estabilidade escapular e anti-rotação.',setup:'Prancha alta, pés afastados.',exec:'Toca ombro oposto sem rodar bacia.',mistake:'Abanar tronco.',reg:'Joelhos no chão.',prog:'Pés juntos.'}
];
const M=[
{key:'A',title:'Peito de assalto',focus:'Peitoral superior + tríceps',ex:['Power Twister press horizontal','Flexão declinada','Power Twister press alto','Flexão diamante']},
{key:'B',title:'Ombros em V',focus:'Deltoide anterior/lateral + serrátil',ex:['Pike push-up','Power Twister overhead press','Pseudo-planche lean','Shoulder taps']},
{key:'C',title:'Costas e postura',focus:'Costas altas + dorsais + bíceps',ex:['Power Twister remada isométrica','Back widow','Prone lat pull','Power Twister curl isométrico']},
{key:'D',title:'Core blindado',focus:'Abdómen espesso + peito superior',ex:['Hollow hold','Leg raises','Mountain climbers','Power Twister press alto']},
{key:'E',title:'Braços densos',focus:'Bíceps + tríceps + antebraço',ex:['Power Twister curl isométrico','Bodyweight triceps extension','Power Twister reverse press','Close-grip push-up']},
{key:'F',title:'Circuito militar 66',focus:'Upper body completo em densidade',ex:['Power Twister press horizontal','Pike push-up','Power Twister remada isométrica','Mountain climbers']},
{key:'R',title:'Recuperação tática',focus:'Mobilidade, técnica, core leve',ex:['Reverse snow angel','Prone lat pull','Shoulder taps','Hollow hold']}
];
function exByName(n){return E.find(e=>e.name===n)||E[0]}
function recoveryScore(){let s=70+(coach.sleep-7)*8+(coach.energy-3)*8-coach.soreness*10; if(coach.sport!=='none')s-=12; return clamp(Math.round(s),20,100)}
function chooseMission(){if(profile.plan&&profile.plan!=='auto')return M.find(m=>m.key===profile.plan)||M[0]; const r=recoveryScore(); if(r<45)return M.find(m=>m.key==='R'); const recent=log.slice(-2).map(x=>x.key); return M.find(m=>!recent.includes(m.key)&&m.key!=='R')||M[(profile.mission-1)%6]}
function workTime(){const r=recoveryScore(); return r>80?50:r>55?45:35} function restTime(){const r=recoveryScore(); return r>80?10:r>55?15:25}
function svg(ex){let c=muscles[ex.group]||'#0a84ff'; return `<svg viewBox="0 0 320 220" role="img"><defs><filter id="sh"><feDropShadow dx="0" dy="8" stdDeviation="8" flood-opacity=".12"/></filter></defs><rect width="320" height="220" rx="20" fill="#f8fafc"/><circle cx="160" cy="45" r="20" fill="#ffd7b5"/><path d="M135 70 Q160 58 185 70 L198 130 Q160 150 122 130 Z" fill="#dbeafe" stroke="#94a3b8" stroke-width="2" filter="url(#sh)"/><path d="M132 78 L80 112" stroke="#94a3b8" stroke-width="18" stroke-linecap="round"/><path d="M188 78 L240 112" stroke="#94a3b8" stroke-width="18" stroke-linecap="round"/><path d="M125 130 L105 190" stroke="#94a3b8" stroke-width="18" stroke-linecap="round"/><path d="M195 130 L215 190" stroke="#94a3b8" stroke-width="18" stroke-linecap="round"/><ellipse cx="160" cy="98" rx="42" ry="26" fill="${ex.group==='peito'?c:'#e2e8f0'}" opacity=".9"/><circle cx="116" cy="78" r="18" fill="${ex.group==='ombros'?c:'#e2e8f0'}"/><circle cx="204" cy="78" r="18" fill="${ex.group==='ombros'?c:'#e2e8f0'}"/><path d="M125 92 L91 115" stroke="${ex.group==='triceps'?c:'#cbd5e1'}" stroke-width="12" stroke-linecap="round"/><path d="M195 92 L229 115" stroke="${ex.group==='triceps'?c:'#cbd5e1'}" stroke-width="12" stroke-linecap="round"/><path d="M145 120 Q160 142 175 120" stroke="${ex.group==='core'?c:'#cbd5e1'}" stroke-width="18" stroke-linecap="round"/><path d="M130 82 Q160 67 190 82" stroke="${ex.group==='costas'?c:'#cbd5e1'}" stroke-width="10" stroke-linecap="round"/><path d="M96 104 Q160 62 224 104" stroke="${ex.name.includes('Power Twister')?'#111827':'transparent'}" stroke-width="8" fill="none" stroke-linecap="round"/><text x="160" y="207" text-anchor="middle" font-size="13" font-weight="800" fill="#475569">${ex.name}</text></svg>`}
function render(){renderToday();renderAcademy();renderCoach();renderBody();renderProgress();$('#missionPill').textContent='M'+String(profile.mission).padStart(3,'0')}
function renderToday(){const m=chooseMission(), r=recoveryScore(); const exs=m.ex.map(exByName); $('#today').innerHTML=`<div class="card"><div class="row"><div><div class="label">Missão ${profile.mission}</div><div class="h2">${m.title}</div><div class="small">${m.focus}</div></div><div class="pill ${r<45?'bad':r<70?'warn':'ok'}">Recovery ${r}%</div></div><div class="bar"><div class="fill" style="width:${(profile.startWeight?((lastWeight()-profile.startWeight)/(profile.targetWeight-profile.startWeight)*100):0)||0}%"></div></div><div class="small">Peso ${lastWeight().toFixed(1)} kg → objetivo ${profile.targetWeight} kg</div></div><div class="card"><div class="exercise" id="curEx">${exs[idx]?.name||exs[0].name}</div><div class="coachline" id="coachLine">${coachText(m,r)}</div><div class="timer" id="timer">${time}</div><div class="small" style="text-align:center" id="phase">${phase==='work'?'TRABALHO':'DESCANSO'} · ${idx+1}/${exs.length}</div><div class="svgbox" id="todaySvg">${svg(exs[idx]||exs[0])}</div><div class="grid2" style="margin-top:12px"><button class="btn primary" id="startBtn">${running?'Pausar':'Iniciar'}</button><button class="btn soft" id="nextBtn">Seguinte</button><button class="btn accent" id="doneBtn">Missão cumprida</button><button class="btn soft" id="resetBtn">Reset</button></div></div><div class="card"><div class="label">Sequência</div><div class="list">${exs.map((e,i)=>`<div class="item ${i===idx?'active':''}"><b>${i+1}. ${e.name}</b><span>${e.why}</span></div>`).join('')}</div></div>`; bindToday(exs,m)}
function coachText(m,r){if(r<45)return 'Hoje o motor reduz volume: técnica limpa, nada de ego. O objetivo é manter consistência.'; if(r>80)return 'Dia pesado. Procura a última repetição com técnica perfeita e excêntrica lenta.'; return 'Dia normal. Mantém 1–2 repetições em reserva e controla a fase de retorno.'}
function bindToday(exs,m){$('#startBtn').onclick=()=>toggle(exs,m); $('#nextBtn').onclick=()=>next(exs); $('#resetBtn').onclick=()=>{running=false;clearInterval(tick);idx=0;phase='work';time=workTime();renderToday()}; $('#doneBtn').onclick=()=>complete(m)}
function toggle(exs,m){running=!running; if(running){clearInterval(tick); tick=setInterval(()=>{time--; if(time<=0)next(exs); updateTimer()},1000)} else clearInterval(tick); renderToday()}
function updateTimer(){let t=$('#timer'); if(t)t.textContent=time; let p=$('#phase'); if(p)p.textContent=`${phase==='work'?'TRABALHO':'DESCANSO'} · ${idx+1}/${chooseMission().ex.length}`}
function next(exs){if(phase==='work'){phase='rest';time=restTime()}else{phase='work';idx=(idx+1)%exs.length;time=workTime()} renderToday(); if(running){clearInterval(tick);tick=setInterval(()=>{time--; if(time<=0)next(exs); updateTimer()},1000)}}
function complete(m){clearInterval(tick);running=false; const d=today(); const same=profile.lastDate===d; if(!same){profile.mission++; profile.xp+=100+recoveryScore(); profile.streak=profile.lastDate?profile.streak+1:1; profile.lastDate=d; log.push({date:d,key:m.key,title:m.title,recovery:recoveryScore(),xp:profile.xp}); save(S.log,log); save(S.profile,profile)} alert('Missão registada. +XP.'); render()}
function renderAcademy(){const groups=['todos','peito','ombros','costas','biceps','triceps','core']; $('#academy').innerHTML=`<div class="card"><div class="label">v27.1 Academia</div><div class="h2">Biblioteca técnica offline</div><div class="small">Imagens SVG, músculos, execução, erros, progressões e “porque funciona”.</div><div class="chips">${groups.map(g=>`<button class="chip ${g==='todos'?'active':''}" data-g="${g}">${g}</button>`).join('')}</div></div><div id="exLib"></div>`; $$('#academy .chip').forEach(b=>b.onclick=()=>{$$('#academy .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');drawLib(b.dataset.g)}); drawLib('todos')}
function drawLib(g){const arr=E.filter(e=>g==='todos'||e.group===g); $('#exLib').innerHTML=arr.map((e,i)=>`<div class="card"><div class="row"><div><div class="label">${e.group} · nível ${e.level}/5</div><div class="h2">${e.name}</div></div><div class="pill">${e.tempo}</div></div><div class="svgbox">${svg(e)}</div><div>${[e.group,...e.sec.split('/')].map(m=>`<span class="muscle"><i class="dot" style="background:${muscles[m]||'#94a3b8'}"></i>${m}</span>`).join('')}</div><div class="list"><div class="item"><b>Execução</b><span>${e.setup} ${e.exec}</span></div><div class="item"><b>Respiração / ritmo</b><span>${e.breath||'Respiração controlada.'}</span></div><div class="item"><b>Erro comum</b><span>${e.mistake}</span></div><div class="item"><b>Regressão / progressão</b><span>${e.reg} → ${e.prog}</span></div><div class="item"><b>Porque funciona</b><span>${e.why}</span></div></div></div>`).join('')}
function renderCoach(){const r=recoveryScore(); $('#coach').innerHTML=`<div class="card"><div class="label">v27.2 Coach offline</div><div class="h2">Motor lógico local, sem API</div><div class="big ${r<45?'bad':r<70?'warn':'ok'}">${r}%</div><div class="small">${r<45?'Recuperação baixa: treino tático.':r<70?'Recuperação razoável: treino normal.':'Recuperação alta: dia bom para carga.'}</div></div><div class="card"><div class="grid2"><div class="field"><label>Sono</label><input id="sleep" type="number" min="3" max="10" step="0.5" value="${coach.sleep}"></div><div class="field"><label>Energia 1–5</label><input id="energy" type="number" min="1" max="5" value="${coach.energy}"></div><div class="field"><label>Dor muscular 0–5</label><input id="soreness" type="number" min="0" max="5" value="${coach.soreness}"></div><div class="field"><label>Outro treino</label><select id="sport"><option value="none">Nenhum</option><option value="karate">Karaté</option><option value="futebol">Futebol</option><option value="trail">Trail</option><option value="natacao">Natação</option></select></div></div><div class="field"><label>Notas livres</label><textarea id="notes" rows="3" placeholder="Ex: ombro direito sensível, turno pesado...">${coach.notes||''}</textarea></div><button class="btn primary" id="saveCoach">Atualizar coach</button></div><div class="card"><div class="label">Decisão de hoje</div><div class="h2">${chooseMission().title}</div><div class="list">${coachRules().map(x=>`<div class="item"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div></div><div class="card"><div class="label">Gémeo digital simplificado</div><div class="small">A app aprende por histórico local: consistência, recuperação, grupos treinados e evolução do peso. Sem internet e sem enviar dados.</div><div class="grid3" style="margin-top:12px"><div class="stat"><b>${log.length}</b><span>missões</span></div><div class="stat"><b>${profile.streak}</b><span>streak</span></div><div class="stat"><b>${Math.round(profile.xp)}</b><span>XP</span></div></div></div>`; $('#sport').value=coach.sport; $('#saveCoach').onclick=()=>{coach={sleep:+$('#sleep').value,energy:+$('#energy').value,soreness:+$('#soreness').value,sport:$('#sport').value,notes:$('#notes').value};save(S.coach,coach);idx=0;phase='work';time=workTime();render()}}
function coachRules(){let a=[]; if(coach.sleep<6)a.push(['Sono baixo','Reduzir volume e aumentar descanso.']); if(coach.soreness>=3)a.push(['Dor muscular alta','Evitar repetir o mesmo padrão intenso.']); if(coach.sport!=='none')a.push(['Outro treino registado','Diminuir carga sistémica hoje.']); if(recoveryScore()>80)a.push(['Recuperação alta','Permitir excêntricas lentas e isometrias finais.']); if(!a.length)a.push(['Estado padrão','Treino normal com 1–2 repetições em reserva.']); return a}
function lastWeight(){return body.length?+body[body.length-1].weight:profile.startWeight}
function renderBody(){const latest=body[body.length-1]||{}; $('#body').innerHTML=`<div class="card"><div class="label">v27.3 Body Analytics</div><div class="h2">Peso, perímetros e fotos</div><div class="grid3" style="margin-top:12px"><div class="stat"><b>${lastWeight().toFixed(1)}</b><span>kg atual</span></div><div class="stat"><b>${(profile.targetWeight-lastWeight()).toFixed(1)}</b><span>kg falta</span></div><div class="stat"><b>${profile.protein}</b><span>g proteína</span></div></div></div><div class="card"><div class="grid2"><div class="field"><label>Peso kg</label><input id="bw" type="number" step="0.1" value="${latest.weight||lastWeight()}"></div><div class="field"><label>Braço cm</label><input id="arm" type="number" step="0.1" value="${latest.arm||''}"></div><div class="field"><label>Peito cm</label><input id="chest" type="number" step="0.1" value="${latest.chest||''}"></div><div class="field"><label>Cintura cm</label><input id="waist" type="number" step="0.1" value="${latest.waist||''}"></div></div><button class="btn primary" id="saveBody">Guardar medidas</button></div><div class="card"><div class="label">Fotos mensais</div><div class="small">Guarda frente/lado/costas sempre com luz e pose semelhantes. A comparação é visual e offline.</div><div class="field"><label>Ângulo</label><select id="angle"><option>frente</option><option>lado</option><option>costas</option></select></div><input id="photoInput" type="file" accept="image/*"><div class="grid2" style="margin-top:12px">${photos.slice(-2).map(p=>`<img class="photo" src="${p.data}">`).join('')||'<div class="small">Sem fotos ainda.</div>'}</div></div><div class="card"><div class="label">Histórico</div><div class="list">${body.slice(-6).reverse().map(b=>`<div class="item"><b>${b.date} · ${b.weight} kg</b><span>Braço ${b.arm||'—'} · Peito ${b.chest||'—'} · Cintura ${b.waist||'—'}</span></div>`).join('')||'<div class="small">Ainda sem medições.</div>'}</div></div>`; $('#saveBody').onclick=()=>{body.push({date:today(),weight:+$('#bw').value,arm:$('#arm').value,chest:$('#chest').value,waist:$('#waist').value});save(S.body,body);render()}; $('#photoInput').onchange=e=>{const f=e.target.files[0]; if(!f)return; const rd=new FileReader(); rd.onload=()=>{photos.push({date:today(),angle:$('#angle').value,data:rd.result}); save(S.photos,photos); renderBody()}; rd.readAsDataURL(f)}}
function renderProgress(){const rank=ranks().findLast(x=>profile.xp>=x.xp)||ranks()[0]; const next=ranks().find(x=>profile.xp<x.xp)||ranks().at(-1); const pct=clamp(profile.xp/next.xp*100,0,100); const gain=lastWeight()-profile.startWeight; $('#progress').innerHTML=`<div class="card"><div class="label">v28 Dashboard</div><div class="rank">${rank.name}</div><div class="small">XP ${profile.xp} / ${next.xp}</div><div class="bar"><div class="fill" style="width:${pct}%"></div></div></div><div class="card"><div class="grid3"><div class="stat"><b>${log.length}</b><span>missões</span></div><div class="stat"><b>${profile.streak}</b><span>streak</span></div><div class="stat"><b>${gain.toFixed(1)}</b><span>kg ganhos</span></div><div class="stat"><b>${Math.round(log.length*15/60)}</b><span>horas</span></div><div class="stat"><b>${Math.round((profile.targetWeight-lastWeight())/0.4)}</b><span>sem. estim.</span></div><div class="stat"><b>${Math.round(log.length/Math.max(1,daysSinceStart())*100)}%</b><span>adesão</span></div></div></div><div class="card"><div class="label">Modelo muscular preditivo</div><div class="h2">${prediction()}</div><div class="small">Baseado apenas nos teus dados locais: peso, missões cumpridas e recovery médio.</div></div><div class="card"><div class="label">Conquistas</div><div class="list">${achievements().map(a=>`<div class="item"><b>${a.ok?'✅':'⬜'} ${a.name}</b><span>${a.desc}</span></div>`).join('')}</div></div>`}
function daysSinceStart(){if(!log.length)return 1; return Math.max(1,Math.round((new Date(today())-new Date(log[0].date))/86400000)+1)}
function prediction(){if(body.length<2)return 'Regista peso semanal para ativar previsão real.'; const first=+body[0].weight, last=lastWeight(), weeks=Math.max(1,(new Date(body.at(-1).date)-new Date(body[0].date))/604800000); const rate=(last-first)/weeks; if(rate<0.05)return 'Ganho lento: provável défice calórico/proteína insuficiente.'; if(rate>0.6)return 'Ganho rápido: vigiar aumento de gordura.'; return `Ritmo adequado: ~${rate.toFixed(2)} kg/semana. Mantém excedente ligeiro e progressão.`}
function ranks(){return[{name:'Recruta',xp:0},{name:'Soldado',xp:700},{name:'Ranger',xp:2000},{name:'Special Forces',xp:4500},{name:'Ghost',xp:8000},{name:'Legend 66',xp:14000}]}
function achievements(){return[{name:'Primeira missão',desc:'Concluir o primeiro treino.',ok:log.length>=1},{name:'30 missões',desc:'Consistência inicial consolidada.',ok:log.length>=30},{name:'100 missões',desc:'Mudança estrutural de hábito.',ok:log.length>=100},{name:'+1 kg',desc:'Primeiro aumento de peso corporal.',ok:lastWeight()>=profile.startWeight+1},{name:'Operação 66',desc:'Chegar aos 66 kg.',ok:lastWeight()>=66}]}
function initTabs(){const tab=localStorage.getItem(S.tab)||'today'; openTab(tab); $$('.tabbtn').forEach(b=>b.onclick=()=>openTab(b.dataset.tab))}
function openTab(t){$$('.tab').forEach(x=>x.classList.toggle('active',x.id===t)); $$('.tabbtn').forEach(x=>x.classList.toggle('active',x.dataset.tab===t)); localStorage.setItem(S.tab,t); if(t==='academy')renderAcademy(); if(t==='coach')renderCoach(); if(t==='body')renderBody(); if(t==='progress')renderProgress()}
initTabs(); time=workTime(); render();
})();
